logging_config:
  log_dir: './log'
  log_label: ''

db_config:
  database: 'database'
  user: 'user'
  password: 'password'

checker_config:
  source_dir: "./source_dir"
  
arsadmin_retriever_config:
  workers_no: 8
  output_dir: './'
  ondemand_instance: 'instance_a'
  ondemand_user: 'user_a'
  